name: cidocker
env:
  TAG: $(date +'%Y-%m-%d_%H-%M')
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: mohanraw/flask:${{ env.TAG }}
