name: Vulnerability Scan

on:
  workflow_run:
    workflows: ["cidocker"]

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull mohanraw/flask:latest

      - uses: dataswift/gha-trivy@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: mohanraw/flask:latest
